import type { NextApiRequest, NextApiResponse } from "next";
import { fetchShopifySkuSales, fetchAmazonBreakdown, SkuRow } from "../../lib/windsor";
import { commitFileContents } from "../../lib/github";

// Heavy: pulls the full SKU history for both channels in small chunks. Amazon's
// connector is slow, so give the function the full serverless budget.
export const config = { maxDuration: 300 };

// GET /api/bake-skus?from=2025-08-01[&to=YYYY-MM-DD]
// Auth: Authorization: Bearer <CRON_SECRET>
// Pulls Shopify (by product) + Amazon (by ASIN) SKU sales for the whole window,
// then commits the result into lib/sku-baseline.ts so it is served statically and
// never re-pulled — the SKU equivalent of baking a completed month into baseline.ts.
function serialize(rows: SkuRow[]): string {
  return rows
    .map(r => `  { name: ${JSON.stringify(r.name)}, units: ${Math.round(r.units)}, revenue: ${Math.round(r.revenue)} },`)
    .join("\n");
}

function buildFile(from: string, to: string, shopify: SkuRow[], amazon: SkuRow[], amazonCat: SkuRow[]): string {
  return `// Saved SKU-level sales baseline — pulled ONCE from Windsor and frozen here,
// exactly like lib/baseline.ts freezes the monthly money metrics. The Products
// tab shows this instantly (zero fetch); only shorter live windows re-pull.
//
// Auto-generated by /api/bake-skus. Re-run that endpoint to refresh/extend.
// Shopify: grouped by product title (corrupt >=50k-unit line items filtered out).
// Amazon: grouped by child ASIN (SKU) and rolled up to 7 categories.

export interface SkuRow { name: string; units: number; revenue: number; }

export const SKU_BASELINE_META = {
  from: ${JSON.stringify(from)},
  to: ${JSON.stringify(to)},
  generatedAt: ${JSON.stringify(new Date().toISOString())},
};

export const SHOPIFY_SKU_BASELINE: SkuRow[] = [
${serialize(shopify)}
];

export const AMAZON_SKU_BASELINE: SkuRow[] = [
${serialize(amazon)}
];

export const AMAZON_CATEGORY_BASELINE: SkuRow[] = [
${serialize(amazonCat)}
];
`;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.headers.authorization !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ ok: false, error: "Unauthorized" });
  }

  const isDate = (s: unknown) => typeof s === "string" && /^\d{4}-\d{2}-\d{2}$/.test(s);
  const from = isDate(req.query.from) ? (req.query.from as string) : "2025-08-01";
  const to   = isDate(req.query.to)   ? (req.query.to as string)   : new Date().toISOString().split("T")[0];

  try {
    // Small chunks + generous per-chunk timeout so the slow amazon_sp connector
    // can complete without any single request blowing the function budget.
    // Amazon SKU + category come from a single pull (fetchAmazonBreakdown).
    const [shopify, amazon] = await Promise.all([
      fetchShopifySkuSales(from, to, 15, 90000).catch(() => [] as SkuRow[]),
      fetchAmazonBreakdown(from, to, 7, 90000).catch(() => ({ skus: [] as SkuRow[], categories: [] as SkuRow[] })),
    ]);

    const file = buildFile(from, to, shopify, amazon.skus, amazon.categories);
    const commit = await commitFileContents(
      "lib/sku-baseline.ts",
      file,
      `Bake SKU baseline ${from}..${to} (auto-committed by /api/bake-skus)`
    );

    return res.status(200).json({
      ok: true,
      from, to,
      shopifyProducts: shopify.length,
      amazonProducts: amazon.skus.length,
      amazonCategories: amazon.categories.length,
      commit,
    });
  } catch (err) {
    return res.status(500).json({ ok: false, error: err instanceof Error ? err.message : String(err) });
  }
}
